"""Write parsed scaffold files to disk and produce a human-readable summary."""
from __future__ import annotations

import os
from pathlib import Path


def write_scaffold(files: dict[str, str], output_dir: str | Path) -> list[str]:
    """Write *files* under *output_dir*, creating parent directories as needed.

    Returns the list of relative paths written (sorted).
    """
    root = Path(output_dir)
    written: list[str] = []

    for rel_path, content in files.items():
        dest = root / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written.append(rel_path)

    return sorted(written)


def format_summary(files: dict[str, str], cloud: str, output_dir: str | Path) -> str:
    """Return a markdown summary suitable for a GitHub Actions workflow summary."""
    root = Path(output_dir)
    written = sorted(files.keys())
    total_lines = sum(content.count("\n") for content in files.values())

    file_list = "\n".join(f"- `{p}`" for p in written)

    return f"""\
## 🏗️ Terraform Scaffold Generated

**Cloud target:** `{cloud}`
**Output directory:** `{root}`
**Files written:** {len(written)}
**Total lines:** {total_lines}

### Files

{file_list}

---
<sub>Generated by [tf-scaffold-ai](https://github.com/JamesIOmete/tf-scaffold-ai)</sub>"""
